######################## default configuration ####################
baseURL = "https://www.sicade.com/"
languageCode = "fr-FR"
title = "SICADE | Métallerie | Tolerie | LiLLE | Hauts de France"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Réalisations"
  URL = "realisations"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Notre Histoire"
  URL = "notre-histoire"
  weight = 3

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 4
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

  ############# footer menu #############
  [[menu.footer]]
  name = "Réalisations"
  URL = "realisations"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Notre Histoire"
  URL = "notre-histoire"
  weight = 3

  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 4

  [[menu.footer]]
  name = "Mentions légales et Politique de Confidentialité"
  URL = "mentions-legales"
  weight = 5

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 6
   
#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Accueil"
# Meta data
description = "Fabrication d'équipements métalliques sur mesure Acier Inox Alu | Lille | Hauts de France | Nord | 59"
author = "Phil K"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/profile-picture.jpg"

# Google Analitycs
googleAnalitycsID = "292489782" # Your ID


# Contact Information
mobile = "0613439523"
email = "contact@sicade.com"
location = "Lille, Hauts de france, Nord, 59, France"
# copyright
copyright = "| Copyright &copy; 2023 [SARL SICADE](https://sicade.com) Tous Droits Réservés |"
# Snipcart Credentials
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-linkedin"
  link = "https://www.linkedin.com/in/philippe-cabotse-56744217b/"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with Netlify.com

  [sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

  